-- =========================================
-- SAMPLE DATA FOR company
-- =========================================
INSERT INTO company (
        reg_no,
        name,
        industry_involved,
        products_and_services,
        company_background,
        logo,
        website,
        ssm_cert,
        remark
    )
VALUES (
        '201901000001',
        'BuildTech Solutions Sdn Bhd',
        'Construction Technology',
        'Construction software and project systems',
        'BuildTech Solutions Sdn Bhd provides digital platforms and software services for construction and engineering firms to improve project coordination, cost tracking, and workflow efficiency.',
        NULL,
        'https://www.buildtech.com.my',
        NULL,
        'Interested in internship collaborations'
    ),
    (
        '201801000002',
        'GreenAxis Engineering Sdn Bhd',
        'Civil Engineering',
        'Infrastructure design and consultancy',
        'GreenAxis Engineering Sdn Bhd is involved in civil and infrastructure consultancy services for transportation, drainage, and urban development projects.',
        NULL,
        'https://www.greenaxis.com.my',
        NULL,
        'Open for graduate hiring'
    ),
    (
        '202001000003',
        'QS Pro Consult Sdn Bhd',
        'Quantity Surveying',
        'Cost planning and tender documentation',
        'QS Pro Consult Sdn Bhd is a quantity surveying consultancy focusing on cost estimation, tendering, procurement, and contract administration.',
        NULL,
        'https://www.qspro.com.my',
        NULL,
        'Suitable for QS students'
    ),
    (
        '201701000004',
        'Urban Matrix Development Berhad',
        'Property Development',
        'Mixed development and property management',
        'Urban Matrix Development Berhad develops residential, commercial, and mixed-use properties across major cities in Malaysia.',
        NULL,
        'https://www.urbanmatrix.com.my',
        NULL,
        'Experienced candidates preferred'
    ),
    (
        '201601000005',
        'InfraNova Builders Sdn Bhd',
        'Construction',
        'Building and infrastructure contracting',
        'InfraNova Builders Sdn Bhd is a contractor handling building construction and public infrastructure works.',
        NULL,
        'https://www.infranova.com.my',
        NULL,
        'Regularly recruits site staff'
    ),
    (
        '202101000006',
        'EcoSpace Design Studio Sdn Bhd',
        'Architecture',
        'Architectural design and sustainability advisory',
        'EcoSpace Design Studio Sdn Bhd is an architectural practice with a focus on green design, sustainable planning, and building performance.',
        NULL,
        'https://www.ecospacedesign.com.my',
        NULL,
        'Good for design-related placements'
    ),
    (
        '201501000007',
        'Pinnacle M&E Services Sdn Bhd',
        'Mechanical and Electrical Engineering',
        'M&E installation and maintenance',
        'Pinnacle M&E Services Sdn Bhd specialises in mechanical and electrical installation works for commercial and institutional buildings.',
        NULL,
        'https://www.pinnacleme.com.my',
        NULL,
        'Requires experienced engineers'
    ),
    (
        '201901000008',
        'TerraCost Consultants Sdn Bhd',
        'Quantity Surveying',
        'Cost estimation and contract administration',
        'TerraCost Consultants Sdn Bhd provides quantity surveying and contract management services for building and civil engineering projects.',
        NULL,
        'https://www.terracost.com.my',
        NULL,
        'Looking for assistant quantity surveyors'
    ),
    (
        '202201000009',
        'SkyBridge Structures Sdn Bhd',
        'Structural Engineering',
        'Structural analysis and detailing',
        'SkyBridge Structures Sdn Bhd provides structural engineering consultancy, design review, and detailing coordination services.',
        NULL,
        'https://www.skybridge.com.my',
        NULL,
        'Pending follow-up'
    ),
    (
        '201301000010',
        'Metro Habitat Holdings Berhad',
        'Property Development',
        'Residential and commercial development',
        'Metro Habitat Holdings Berhad is an established developer involved in housing, retail, and integrated township projects.',
        NULL,
        'https://www.metrohabitat.com.my',
        NULL,
        'Active hiring for management roles'
    ),
    (
        '202001000011',
        'SolidEarth Geotechnics Sdn Bhd',
        'Geotechnical Engineering',
        'Soil investigation and foundation design',
        'SolidEarth Geotechnics Sdn Bhd supports construction projects through geotechnical investigation, reporting, and foundation advisory.',
        NULL,
        'https://www.solidearth.com.my',
        NULL,
        'Accepts engineering interns'
    ),
    (
        '201801000012',
        'PrimeWorks Project Management Sdn Bhd',
        'Project Management',
        'Project coordination and planning services',
        'PrimeWorks Project Management Sdn Bhd provides project planning, scheduling, monitoring, and coordination services.',
        NULL,
        'https://www.primeworks.com.my',
        NULL,
        'Good opportunity for fresh graduates'
    ),
    (
        '201701000013',
        'Apex Rail Systems Sdn Bhd',
        'Transportation Infrastructure',
        'Railway systems and trackwork services',
        'Apex Rail Systems Sdn Bhd undertakes rail infrastructure works, systems support, and maintenance services.',
        NULL,
        'https://www.apexrail.com.my',
        NULL,
        'Technical roles available'
    ),
    (
        '202101000014',
        'BluePeak BIM Solutions Sdn Bhd',
        'Building Information Modelling',
        'BIM modelling and coordination services',
        'BluePeak BIM Solutions Sdn Bhd supports construction professionals through BIM modelling, clash detection, and coordination.',
        NULL,
        'https://www.bluepeakbim.com.my',
        NULL,
        'Strong fit for IT and construction students'
    ),
    (
        '201901000015',
        'HarborView Construction Sdn Bhd',
        'Construction',
        'Commercial building construction',
        'HarborView Construction Sdn Bhd is a contractor delivering office, retail, and mixed-use commercial projects.',
        NULL,
        'https://www.harborview.com.my',
        NULL,
        'Currently inactive for recruitment'
    ),
    (
        '201601000016',
        'Crestline Facilities Management Sdn Bhd',
        'Facilities Management',
        'Building operation and maintenance',
        'Crestline Facilities Management Sdn Bhd manages building maintenance, asset upkeep, and operational support services.',
        NULL,
        'https://www.crestlinefm.com.my',
        NULL,
        'FM-related vacancies available'
    ),
    (
        '202201000017',
        'Vertex Planning Consult Sdn Bhd',
        'Town Planning',
        'Planning submissions and development advisory',
        'Vertex Planning Consult Sdn Bhd provides development planning consultancy and authority submission services.',
        NULL,
        'https://www.vertexplanning.com.my',
        NULL,
        'Small firm with limited intake'
    ),
    (
        '201401000018',
        'Maju Jaya Material Supply Sdn Bhd',
        'Building Materials',
        'Supply of cement, steel, and finishing materials',
        'Maju Jaya Material Supply Sdn Bhd supplies construction materials to contractors, developers, and project sites.',
        NULL,
        'https://www.majujaya.com.my',
        NULL,
        'May need procurement assistants'
    ),
    (
        '201801000019',
        'Nexus Water Engineering Sdn Bhd',
        'Water Infrastructure',
        'Water treatment and pipeline systems',
        'Nexus Water Engineering Sdn Bhd undertakes water treatment plant, pipeline, and utility infrastructure works.',
        NULL,
        'https://www.nexuswater.com.my',
        NULL,
        'Suspended profile'
    ),
    (
        '202301000020',
        'FutureGrid Energy Solutions Sdn Bhd',
        'Renewable Energy',
        'Solar systems and energy efficiency solutions',
        'FutureGrid Energy Solutions Sdn Bhd provides renewable energy and energy-saving systems for commercial and industrial users.',
        NULL,
        'https://www.futuregrid.com.my',
        NULL,
        'Open to sustainability-related placements'
    );
-- =========================================
-- SAMPLE DATA FOR companybranch
-- =========================================
INSERT INTO companybranch (
        company_id,
        address_line,
        city,
        state,
        postcode,
        country,
        total_no_of_staff,
        vacancy_level,
        status,
        visibility,
        last_visit,
        last_contact,
        is_hq
    )
VALUES (
        1,
        'Level 12, Menara Sentral, Jalan Tun Sambanthan',
        'Kuala Lumpur',
        'Wilayah Persekutuan Kuala Lumpur',
        '50470',
        'Malaysia',
        30,
        'Internship',
        1,
        1,
        '2026-03-20',
        '2026-03-18',
        1
    ),
    (
        1,
        'No. 18, Jalan Teknologi 3/4, Taman Sains Selangor',
        'Petaling Jaya',
        'Selangor',
        '47810',
        'Malaysia',
        15,
        'Entry',
        1,
        1,
        '2026-03-15',
        '2026-03-12',
        0
    ),
    (
        2,
        'No. 25, Jalan SS 2/24, SS 2',
        'Petaling Jaya',
        'Selangor',
        '47300',
        'Malaysia',
        35,
        'Entry',
        1,
        1,
        '2026-03-22',
        '2026-03-19',
        1
    ),
    (
        2,
        'Lot 8, Persiaran Perusahaan, Seksyen 23',
        'Shah Alam',
        'Selangor',
        '40300',
        'Malaysia',
        25,
        'Internship',
        1,
        1,
        '2026-03-16',
        '2026-03-13',
        0
    ),
    (
        3,
        'Suite 9-3, Wisma UOA, Jalan Pinang',
        'Kuala Lumpur',
        'Wilayah Persekutuan Kuala Lumpur',
        '50450',
        'Malaysia',
        18,
        'Internship',
        1,
        1,
        '2026-03-15',
        '2026-03-10',
        1
    ),
    (
        3,
        'No. 11, Jalan Molek 1/10, Taman Molek',
        'Johor Bahru',
        'Johor',
        '81100',
        'Malaysia',
        10,
        'Entry',
        1,
        1,
        '2026-03-12',
        '2026-03-09',
        0
    ),
    (
        4,
        'Menara Metro, Jalan Sultan Ismail',
        'Kuala Lumpur',
        'Wilayah Persekutuan Kuala Lumpur',
        '50250',
        'Malaysia',
        90,
        'Senior',
        1,
        1,
        '2026-03-17',
        '2026-03-14',
        1
    ),
    (
        4,
        'No. 6, Jalan Bestari 5/2, Bandar Bestari',
        'Klang',
        'Selangor',
        '41200',
        'Malaysia',
        50,
        'Entry',
        1,
        1,
        '2026-03-13',
        '2026-03-11',
        0
    ),
    (
        4,
        'No. 88, Jalan Austin Heights 8/3',
        'Johor Bahru',
        'Johor',
        '81100',
        'Malaysia',
        40,
        'Entry',
        1,
        1,
        '2026-03-11',
        '2026-03-10',
        0
    ),
    (
        5,
        'Lot 17, Jalan Industri Utama 2',
        'Seremban',
        'Negeri Sembilan',
        '70400',
        'Malaysia',
        55,
        'Entry',
        1,
        1,
        '2026-03-21',
        '2026-03-16',
        1
    ),
    (
        5,
        'No. 102, Jalan Gopeng',
        'Ipoh',
        'Perak',
        '31350',
        'Malaysia',
        40,
        'Internship',
        1,
        1,
        '2026-03-18',
        '2026-03-15',
        0
    ),
    (
        6,
        'No. 3A, Jalan Kenari 11, Bandar Puchong Jaya',
        'Puchong',
        'Selangor',
        '47170',
        'Malaysia',
        22,
        'Internship',
        1,
        1,
        '2026-03-13',
        '2026-03-11',
        1
    ),
    (
        7,
        'No. 45, Jalan 51A/223',
        'Petaling Jaya',
        'Selangor',
        '46100',
        'Malaysia',
        45,
        'Senior',
        1,
        1,
        '2026-03-24',
        '2026-03-20',
        1
    ),
    (
        7,
        'Ground Floor, Block C, Jalan Dato Keramat',
        'Kuala Lumpur',
        'Wilayah Persekutuan Kuala Lumpur',
        '54000',
        'Malaysia',
        30,
        'Entry',
        1,
        1,
        '2026-03-19',
        '2026-03-16',
        0
    ),
    (
        8,
        'Unit 7-5, Wisma Zelan, Jalan Tasik Permaisuri 2',
        'Cheras',
        'Wilayah Persekutuan Kuala Lumpur',
        '56000',
        'Malaysia',
        20,
        'Entry',
        1,
        1,
        '2026-03-18',
        '2026-03-15',
        1
    ),
    (
        8,
        'No. 29, Jalan Sutera Tanjung 8/4',
        'Skudai',
        'Johor',
        '81300',
        'Malaysia',
        14,
        'Internship',
        1,
        1,
        '2026-03-14',
        '2026-03-12',
        0
    ),
    (
        9,
        'No. 77, Jalan Bukit Gambir',
        'George Town',
        'Pulau Pinang',
        '11700',
        'Malaysia',
        40,
        'Internship',
        0,
        1,
        '2026-03-14',
        '2026-03-12',
        1
    ),
    (
        10,
        'Level 20, Menara Habitat, Jalan Ampang',
        'Kuala Lumpur',
        'Wilayah Persekutuan Kuala Lumpur',
        '50450',
        'Malaysia',
        150,
        'Senior',
        1,
        1,
        '2026-03-19',
        '2026-03-17',
        1
    ),
    (
        10,
        'No. 14, Jalan Bayan Lepas 2',
        'Bayan Lepas',
        'Pulau Pinang',
        '11900',
        'Malaysia',
        90,
        'Entry',
        1,
        1,
        '2026-03-16',
        '2026-03-14',
        0
    ),
    (
        11,
        'No. 12, Jalan Universiti, Seksyen 13',
        'Shah Alam',
        'Selangor',
        '40100',
        'Malaysia',
        18,
        'Internship',
        1,
        1,
        '2026-03-16',
        '2026-03-13',
        1
    ),
    (
        11,
        'Lot 31, Jalan Kuching',
        'Kuching',
        'Sarawak',
        '93100',
        'Malaysia',
        12,
        'Entry',
        1,
        1,
        '2026-03-11',
        '2026-03-09',
        0
    ),
    (
        12,
        'No. 8, Jalan Permas 10/7',
        'Masai',
        'Johor',
        '81750',
        'Malaysia',
        52,
        'Entry',
        1,
        1,
        '2026-03-11',
        '2026-03-09',
        1
    ),
    (
        13,
        'Block B, Technology Park Malaysia, Bukit Jalil',
        'Kuala Lumpur',
        'Wilayah Persekutuan Kuala Lumpur',
        '57000',
        'Malaysia',
        70,
        'Senior',
        1,
        1,
        '2026-03-25',
        '2026-03-21',
        1
    ),
    (
        13,
        'No. 20, Jalan Metro Perdana Barat 1',
        'Kepong',
        'Wilayah Persekutuan Kuala Lumpur',
        '52100',
        'Malaysia',
        50,
        'Entry',
        1,
        1,
        '2026-03-22',
        '2026-03-19',
        0
    ),
    (
        14,
        'No. 55, Jalan Setia Tropika 1/1',
        'Johor Bahru',
        'Johor',
        '81200',
        'Malaysia',
        14,
        'Internship',
        1,
        1,
        '2026-03-10',
        '2026-03-08',
        1
    ),
    (
        14,
        'Level 3, Menara Mutiara, Jalan Raja Chulan',
        'Kuala Lumpur',
        'Wilayah Persekutuan Kuala Lumpur',
        '50200',
        'Malaysia',
        12,
        'Entry',
        1,
        1,
        '2026-03-08',
        '2026-03-07',
        0
    ),
    (
        15,
        'No. 26, Jalan Bukit Minyak 3',
        'Bukit Mertajam',
        'Pulau Pinang',
        '14000',
        'Malaysia',
        88,
        'Entry',
        2,
        1,
        '2026-03-12',
        '2026-03-10',
        1
    ),
    (
        16,
        'No. 91, Jalan Tuanku Abdul Rahman',
        'Kuala Lumpur',
        'Wilayah Persekutuan Kuala Lumpur',
        '50100',
        'Malaysia',
        65,
        'Senior',
        1,
        1,
        '2026-03-23',
        '2026-03-20',
        1
    ),
    (
        16,
        'No. 7, Jalan Diplomatik 2/1, Presint 15',
        'Putrajaya',
        'Wilayah Persekutuan Putrajaya',
        '62050',
        'Malaysia',
        45,
        'Entry',
        1,
        1,
        '2026-03-18',
        '2026-03-16',
        0
    ),
    (
        17,
        'No. 5, Jalan Austin Perdana 2',
        'Johor Bahru',
        'Johor',
        '81100',
        'Malaysia',
        18,
        'Internship',
        1,
        1,
        '2026-03-20',
        '2026-03-17',
        1
    ),
    (
        18,
        'Lot 10, Jalan Perusahaan Sungai Lokan',
        'Butterworth',
        'Pulau Pinang',
        '13400',
        'Malaysia',
        42,
        'Entry',
        1,
        1,
        '2026-03-09',
        '2026-03-07',
        1
    ),
    (
        18,
        'No. 33, Jalan Pending',
        'Kuching',
        'Sarawak',
        '93450',
        'Malaysia',
        25,
        'Internship',
        1,
        1,
        '2026-03-06',
        '2026-03-05',
        0
    ),
    (
        19,
        'No. 60, Jalan Sungai Besi',
        'Kuala Lumpur',
        'Wilayah Persekutuan Kuala Lumpur',
        '57100',
        'Malaysia',
        40,
        'Senior',
        3,
        0,
        '2026-03-26',
        '2026-03-22',
        1
    ),
    (
        19,
        'No. 9, Jalan Lapangan Terbang',
        'Kota Kinabalu',
        'Sabah',
        '88200',
        'Malaysia',
        33,
        'Entry',
        3,
        0,
        '2026-03-21',
        '2026-03-19',
        0
    ),
    (
        20,
        'No. 18, Jalan Solaris 4, Solaris Mont Kiara',
        'Kuala Lumpur',
        'Wilayah Persekutuan Kuala Lumpur',
        '50480',
        'Malaysia',
        20,
        'Internship',
        1,
        1,
        '2026-03-27',
        '2026-03-23',
        1
    ),
    (
        20,
        'No. 21, Jalan Permata 2',
        'Cyberjaya',
        'Selangor',
        '63000',
        'Malaysia',
        15,
        'Entry',
        1,
        1,
        '2026-03-24',
        '2026-03-21',
        0
    );