-- COHORT DATA
INSERT INTO cohort (
        description,
        startDate,
        endDate,
        level,
        isActive,
        report1DueDate,
        report2DueDate,
        report3DueDate,
        report4DueDate,
        report5DueDate,
        finalReportDueDate,
        examStartDate,
        examEndDate,
        companyEvaluationDate,
        reportMonth1,
        reportMonth2,
        reportMonth3,
        reportMonth4,
        reportMonth5,
        reportMonth6,
        campus,
        faculty,
        personInCharge,
        pidEmail
    )
VALUES (
        'Cohort Jan–Jun 2025 (Level 1)',
        '2025-01-06',
        '2025-06-20',
        1,
        0,
        '2025-01-31',
        '2025-02-28',
        '2025-03-31',
        '2025-04-30',
        '2025-05-31',
        '2025-06-10',
        '2025-06-12',
        '2025-06-20',
        '2025-06-05',
        'January',
        'February',
        'March',
        'April',
        'May',
        'June',
        'Johor Branch Campus',
        'Faculty of Built Environment',
        'Dr. Aisha Rahman',
        'aisha.rahman@utm.my'
    ),
    (
        'Cohort Jul–Dec 2025 (Level 1)',
        '2025-07-07',
        '2025-12-19',
        1,
        0,
        '2025-07-31',
        '2025-08-31',
        '2025-09-30',
        '2025-10-31',
        '2025-11-30',
        '2025-12-08',
        '2025-12-10',
        '2025-12-19',
        '2025-12-03',
        'July',
        'August',
        'September',
        'October',
        'November',
        'December',
        'Johor Branch Campus',
        'Faculty of Computing and Information Technology',
        'Mr. Hafiz Ismail',
        'hafiz.ismail@utm.my'
    ),
    (
        'Cohort Feb–Jul 2026 (Level 2)',
        '2026-02-02',
        '2026-07-17',
        2,
        1,
        '2026-02-28',
        '2026-03-31',
        '2026-04-30',
        '2026-05-31',
        '2026-06-30',
        '2026-07-07',
        '2026-07-09',
        '2026-07-17',
        '2026-07-03',
        'February',
        'March',
        'April',
        'May',
        'June',
        'July',
        'Kuala Lumpur Main Campus',
        'Faculty of Engineering and Technology',
        'Ir. Siti Nurul',
        'siti.nurul@utm.my'
    ),
    (
        'Cohort Mar–Aug 2026 (Level 2)',
        '2026-03-09',
        '2026-08-21',
        2,
        1,
        '2026-03-31',
        '2026-04-30',
        '2026-05-31',
        '2026-06-30',
        '2026-07-31',
        '2026-08-10',
        '2026-08-12',
        '2026-08-21',
        '2026-08-06',
        'March',
        'April',
        'May',
        'June',
        'July',
        'August',
        'Johor Branch Campus',
        'Faculty of Business and Finance',
        'Dr. Lim Wei Jian',
        'limweijian@utm.my'
    ),
    (
        'Cohort Sep 2026–Feb 2027 (Level 3)',
        '2026-09-07',
        '2027-02-19',
        3,
        0,
        '2026-09-30',
        '2026-10-31',
        '2026-11-30',
        '2026-12-31',
        '2027-01-31',
        '2027-02-09',
        '2027-02-11',
        '2027-02-19',
        '2027-02-05',
        'September',
        'October',
        'November',
        'December',
        'January',
        'February',
        'Kuala Lumpur Main Campus',
        'Faculty of Social Science and Humanities',
        'Ms. Noraini Salleh',
        'noraini.salleh@utm.my'
    );
-- SYSUSER DATA
INSERT INTO sysuser (
        email,
        username,
        password,
        role,
        ic_number,
        application_id,
        is_active,
        is_locked,
        login_attempts,
        last_login_at,
        password_changed_at,
        email_verified_at
    )
VALUES -- Committee (no IC, password set to a placeholder since rule applies to IC users)
    (
        'supervisor1@univ.edu.my',
        'sv_rahman',
        'supervisor123',
        'supervisor',
        NULL,
        NULL,
        TRUE,
        FALSE,
        1,
        '2026-02-24 14:30:00',
        '2026-01-15 10:20:00',
        '2026-01-15 10:25:00'
    ),
    (
        'committee2@univ.edu.my',
        'committee2',
        'committee123',
        'committee',
        NULL,
        NULL,
        TRUE,
        FALSE,
        0,
        '2026-02-26 10:15:00',
        '2026-02-02 08:00:00',
        '2026-02-02 08:05:00'
    ),
    (
        'committee3@univ.edu.my',
        'committee3',
        'committee123',
        'committee',
        NULL,
        NULL,
        TRUE,
        FALSE,
        1,
        '2026-02-27 11:20:00',
        '2026-02-03 08:00:00',
        '2026-02-03 08:05:00'
    ),
    (
        'committee4@univ.edu.my',
        'committee4',
        'committee123',
        'committee',
        NULL,
        NULL,
        TRUE,
        FALSE,
        0,
        '2026-02-28 14:30:00',
        '2026-02-04 08:00:00',
        '2026-02-04 08:05:00'
    ),
    -- Students (password = ic_number without '-')
    (
        'a23be0123@utm.my',
        'aisyah_hassan',
        '020304101111',
        'student',
        '020304-10-1111',
        NULL,
        TRUE,
        FALSE,
        0,
        '2026-02-26 08:05:00',
        '2026-02-10 12:00:00',
        '2026-02-10 12:10:00'
    ),
    (
        'a23be0456@utm.my',
        'izzat_razak',
        '990102012222',
        'student',
        '990102-01-2222',
        NULL,
        TRUE,
        FALSE,
        1,
        '2026-02-23 20:12:00',
        '2026-02-05 09:45:00',
        NULL
    ),
    (
        'student3@univ.edu.my',
        'lisa_qs',
        '000505052468',
        'student',
        '000505-05-2468',
        NULL,
        FALSE,
        TRUE,
        5,
        NULL,
        '2026-01-20 16:00:00',
        NULL
    );
-- Pick a creator (committee-enabled university supervisor if available, else any university supervisor)
SET @creator_staff_id = COALESCE(
        (
            SELECT staffId
            FROM ucsupervisor
            WHERE isCommittee = 1
            ORDER BY staffId
            LIMIT 1
        ), (
            SELECT staffId
            FROM ucsupervisor
            ORDER BY staffId
            LIMIT 1
        )
    );
-- Pick an active cohort if available (can be NULL if no cohort yet)
SET @active_cohort_id = (
        SELECT cohort_id
        FROM cohort
        WHERE isActive = 1
        ORDER BY startDate DESC
        LIMIT 1
    );
-- Insert 5 announcements
INSERT INTO announcement (
        created_by_staff_id,
        title,
        message,
        target_role,
        cohort_id,
        faculty,
        campus,
        is_published,
        publish_at,
        expire_at
    )
VALUES (
        @creator_staff_id,
        'System Notice: Portal Maintenance',
        'The internship portal will undergo maintenance this weekend. Some services may be unavailable during this period. Please plan your submissions earlier to avoid disruption.',
        'all',
        NULL,
        NULL,
        NULL,
        1,
        NOW(),
        DATE_ADD(NOW(), INTERVAL 7 DAY)
    ),
    (
        @creator_staff_id,
        'Reminder: Progress Report Submission',
        'This is a reminder to submit your monthly progress report before the due date. Late submissions may affect your status and evaluation.',
        'student',
        @active_cohort_id,
        NULL,
        NULL,
        1,
        NOW(),
        DATE_ADD(NOW(), INTERVAL 14 DAY)
    ),
    (
        @creator_staff_id,
        'Internship Briefing Session',
        'A briefing session will be held for students to explain the internship process, document requirements, and evaluation method. Please check your timetable and attend.',
        'student',
        @active_cohort_id,
        'Faculty of Built Environment',
        'Johor Branch Campus',
        1,
        NOW(),
        DATE_ADD(NOW(), INTERVAL 30 DAY)
    ),
    (
        @creator_staff_id,
        'Supervisor Notice: Student Evaluation Window',
        'The student evaluation window is now open. Please complete the assessment marks and comments before the closing date.',
        'supervisor',
        @active_cohort_id,
        NULL,
        NULL,
        1,
        NOW(),
        DATE_ADD(NOW(), INTERVAL 21 DAY)
    ),
    (
        @creator_staff_id,
        'Document Verification Update',
        'Committee will review submitted documents (acceptance form, acknowledgement, and supporting evidence). Please ensure your uploads are clear and complete.',
        'all',
        @active_cohort_id,
        NULL,
        NULL,
        1,
        NOW(),
        NULL
    );
INSERT INTO studentapplication (
        number_ic,
        studentID,
        studentName,
        gender,
        studentEmail,
        contactDate,
        comName,
        comAddress,
        comSupervisor,
        comSupervisorEmail,
        comSupervisorContact,
        allowance,
        ucSupervisor,
        ucSupervisorEmail,
        ucSupervisorContact,
        applyStatus,
        remark,
        level,
        cohortId,
        programme,
        groupNo,
        CGPA,
        ownTransport,
        tempAddress,
        personalEmail,
        permanentAddress,
        permanentContact,
        healthRemark,
        programmingKnowledge,
        databaseKnowledge,
        networkingKnowledge,
        templateVersion,
        formAcceptance,
        formAcknowledgement,
        letterIdentity,
        otherEvidence,
        doVerifier,
        doVerifierEmail,
        isAgreed
    )
VALUES (
        '020304-10-1111',
        'A23BE0123',
        'Nur Aisyah Binti Hassan',
        'F',
        'a23be0123@utm.my',
        '2026-02-18',
        'Alpha Build Sdn Bhd',
        'No. 21, Jalan Universiti 1, 81300 Skudai, Johor, Malaysia',
        'Encik Faizal Ismail',
        'faizal@alphabuild.com.my',
        '013-2223344',
        900.00,
        'sv_rahman',
        'supervisor1@univ.edu.my',
        '011-7788990',
        'approved',
        'Approved after placement confirmation.',
        4,
        3,
        'BEQS',
        2,
        3.45,
        1,
        'Kolej Canselor, UTM Skudai, 81310 Johor Bahru, Johor',
        'aisyah.hassan@gmail.com',
        'No. 5, Jalan Sutera 3, 81100 Johor Bahru, Johor, Malaysia',
        '019-5544332',
        'No known health issues.',
        'Intermediate',
        'Intermediate',
        'Basic',
        1,
        'Accepted via online form on 2026-02-18',
        'Acknowledged by student on 2026-02-18',
        'OFFER-2026-0102',
        'offer_letter_aisyah.pdf',
        'Pn Siti Nur Aina',
        'siti.aina@utm.my',
        1
    ),
    (
        '990102-01-2222',
        'A23BE0456',
        'Muhammad Izzat Bin Razak',
        'M',
        'a23be0456@utm.my',
        '2026-02-20',
        'Mega QS Consultancy',
        'Suite 8-3, Menara City, Jalan Damansara, 50490 Kuala Lumpur, Malaysia',
        'Ms Tan Mei Ling',
        'meiling.tan@megaqs.com.my',
        '012-8887766',
        750.00,
        'sv_rahman',
        'supervisor1@univ.edu.my',
        '011-7788990',
        'pending',
        'Awaiting company final confirmation.',
        4,
        1,
        'BEQS',
        4,
        3.21,
        0,
        'Kolej Tun Razak, UTM Skudai, 81310 Johor Bahru, Johor',
        'izzat.razak@gmail.com',
        'No. 18, Jalan Merpati 2, 43000 Kajang, Selangor, Malaysia',
        '017-1122334',
        'Allergic to seafood (mild).',
        'Basic',
        'Intermediate',
        'Intermediate',
        1,
        'Accepted via online form on 2026-02-20',
        'Acknowledged by student on 2026-02-20',
        'OFFER-2026-0103',
        'offer_letter_izzat.pdf',
        'Pn Siti Nur Aina',
        'siti.aina@utm.my',
        1
    ),
    (
        '000505-05-2468',
        'A23QS0001',
        'Lisa Tan',
        'F',
        'student3@univ.edu.my',
        '2026-03-01',
        'N/A',
        'N/A',
        'N/A',
        'N/A',
        'N/A',
        0.00,
        'sv_default',
        'N/A',
        'N/A',
        'pending',
        'Account is locked due to multiple failed login attempts.',
        3,
        1,
        'QS',
        1,
        3.20,
        1,
        'Hostel Block A',
        'lisa.personal@gmail.com',
        'No. 10, Jalan Example, Melaka',
        '012-3456789',
        'No known issues.',
        'Basic',
        'Basic',
        'Basic',
        1,
        'Accepted via system',
        'Acknowledged by student',
        'N/A',
        'N/A',
        'Admin Officer',
        'admin@univ.edu.my',
        1
    );
INSERT INTO ucsupervisor (
        staffId,
        name,
        email,
        password,
        remark,
        isActive,
        isCommittee,
        faculty,
        campus
    )
VALUES (
        'US001',
        'Dr. Lim Wei Chen',
        'weichen.lim@university.edu',
        'hashed_password_123',
        'Senior Supervisor',
        1,
        1,
        'Faculty of Built Environment',
        'Kuala Lumpur Main Campus'
    ),
    (
        'US002',
        'Prof. Tan Jia Ming',
        'jiaming.tan@university.edu',
        'hashed_password_456',
        'Internship Coordinator',
        1,
        1,
        'Faculty of Accountancy, Finance and Business',
        'Penang Branch Campus'
    ),
    (
        'US003',
        'Dr. Aisha Rahman',
        'aisha.rahman@university.edu',
        'hashed_password_789',
        'Part-time Supervisor',
        1,
        0,
        'Faculty of Computing and Information Technology',
        'Kuala Lumpur Main Campus'
    );
INSERT INTO progressreport (
        applicantId,
        cohortId,
        reportType,
        reportNo,
        dueDate,
        status,
        remark,
        file_path
    )
VALUES (
        1,
        1,
        'progress',
        1,
        '2026-03-10',
        2,
        'Approved by supervisor',
        '/uploads/s1_p1.pdf'
    ),
    (
        1,
        1,
        'progress',
        2,
        '2026-03-24',
        1,
        'Submitted',
        '/uploads/s1_p2.pdf'
    ),
    (
        1,
        1,
        'progress',
        3,
        '2026-04-07',
        0,
        'Pending submission',
        NULL
    ),
    (
        1,
        1,
        'final',
        NULL,
        '2026-06-30',
        1,
        'Final report not submitted',
        NULL
    ),
    (
        2,
        1,
        'progress',
        1,
        '2026-03-10',
        2,
        'Good progress',
        '/uploads/s2_p1.pdf'
    ),
    (
        2,
        1,
        'progress',
        2,
        '2026-03-24',
        2,
        'Approved',
        '/uploads/s2_p2.pdf'
    ),
    (
        2,
        1,
        'progress',
        3,
        '2026-04-07',
        1,
        'Submitted',
        '/uploads/s2_p3.pdf'
    ),
    (
        2,
        1,
        'final',
        NULL,
        '2026-06-30',
        0,
        'Awaiting final report',
        NULL
    );
INSERT INTO blacklistcompany (
        created_at,
        comName,
        address,
        reason,
        byCommittee,
        attachment,
        is_removed,
        removed_at
    )
VALUES (
        NOW(),
        'Selatan Logistics & Warehouse Sdn Bhd',
        'PTD 10188, Jalan Gudang 5, Kawasan Perindustrian Pasir Gudang, 81700 Pasir Gudang, Johor',
        'Multiple complaints from interns regarding excessive working hours and unsafe warehouse conditions.',
        'committee1',
        'selatan_logistics_report.pdf',
        0,
        NULL
    ),
    (
        NOW(),
        'Rimbun Food Manufacturing Sdn Bhd',
        'Lot 8, Jalan Industri Ringan 1, Kawasan Industri Ringan Senai, 81400 Senai, Johor',
        'Failed to comply with hygiene and safety standards during student placement evaluation.',
        'committee1',
        'rimbun_food_audit.pdf',
        0,
        NULL
    ),
    (
        NOW(),
        'Bumi Agro Supplies Sdn Bhd',
        'Lot 22, Jalan Bukit Pasir, Bukit Pasir, 84200 Muar, Johor',
        'Did not provide structured training program and assigned unrelated manual tasks to interns.',
        'committee1',
        'bumi_agro_feedback.docx',
        0,
        NULL
    );
-- =========================================
-- SAMPLE DATA FOR company
-- =========================================
INSERT INTO company (
        reg_no,
        name,
        industry_involved,
        products_and_services,
        company_background,
        logo,
        website,
        ssm_cert,
        remark
    )
VALUES (
        '201901000001',
        'BuildTech Solutions Sdn Bhd',
        'Construction Technology',
        'Construction software and project systems',
        'BuildTech Solutions Sdn Bhd provides digital platforms and software services for construction and engineering firms to improve project coordination, cost tracking, and workflow efficiency.',
        NULL,
        'https://www.buildtech.com.my',
        NULL,
        'Interested in internship collaborations'
    ),
    (
        '201801000002',
        'GreenAxis Engineering Sdn Bhd',
        'Civil Engineering',
        'Infrastructure design and consultancy',
        'GreenAxis Engineering Sdn Bhd is involved in civil and infrastructure consultancy services for transportation, drainage, and urban development projects.',
        NULL,
        'https://www.greenaxis.com.my',
        NULL,
        'Open for graduate hiring'
    ),
    (
        '202001000003',
        'QS Pro Consult Sdn Bhd',
        'Quantity Surveying',
        'Cost planning and tender documentation',
        'QS Pro Consult Sdn Bhd is a quantity surveying consultancy focusing on cost estimation, tendering, procurement, and contract administration.',
        NULL,
        'https://www.qspro.com.my',
        NULL,
        'Suitable for QS students'
    ),
    (
        '201701000004',
        'Urban Matrix Development Berhad',
        'Property Development',
        'Mixed development and property management',
        'Urban Matrix Development Berhad develops residential, commercial, and mixed-use properties across major cities in Malaysia.',
        NULL,
        'https://www.urbanmatrix.com.my',
        NULL,
        'Experienced candidates preferred'
    ),
    (
        '201601000005',
        'InfraNova Builders Sdn Bhd',
        'Construction',
        'Building and infrastructure contracting',
        'InfraNova Builders Sdn Bhd is a contractor handling building construction and public infrastructure works.',
        NULL,
        'https://www.infranova.com.my',
        NULL,
        'Regularly recruits site staff'
    ),
    (
        '202101000006',
        'EcoSpace Design Studio Sdn Bhd',
        'Architecture',
        'Architectural design and sustainability advisory',
        'EcoSpace Design Studio Sdn Bhd is an architectural practice with a focus on green design, sustainable planning, and building performance.',
        NULL,
        'https://www.ecospacedesign.com.my',
        NULL,
        'Good for design-related placements'
    ),
    (
        '201501000007',
        'Pinnacle M&E Services Sdn Bhd',
        'Mechanical and Electrical Engineering',
        'M&E installation and maintenance',
        'Pinnacle M&E Services Sdn Bhd specialises in mechanical and electrical installation works for commercial and institutional buildings.',
        NULL,
        'https://www.pinnacleme.com.my',
        NULL,
        'Requires experienced engineers'
    ),
    (
        '201901000008',
        'TerraCost Consultants Sdn Bhd',
        'Quantity Surveying',
        'Cost estimation and contract administration',
        'TerraCost Consultants Sdn Bhd provides quantity surveying and contract management services for building and civil engineering projects.',
        NULL,
        'https://www.terracost.com.my',
        NULL,
        'Looking for assistant quantity surveyors'
    ),
    (
        '202201000009',
        'SkyBridge Structures Sdn Bhd',
        'Structural Engineering',
        'Structural analysis and detailing',
        'SkyBridge Structures Sdn Bhd provides structural engineering consultancy, design review, and detailing coordination services.',
        NULL,
        'https://www.skybridge.com.my',
        NULL,
        'Pending follow-up'
    ),
    (
        '201301000010',
        'Metro Habitat Holdings Berhad',
        'Property Development',
        'Residential and commercial development',
        'Metro Habitat Holdings Berhad is an established developer involved in housing, retail, and integrated township projects.',
        NULL,
        'https://www.metrohabitat.com.my',
        NULL,
        'Active hiring for management roles'
    ),
    (
        '202001000011',
        'SolidEarth Geotechnics Sdn Bhd',
        'Geotechnical Engineering',
        'Soil investigation and foundation design',
        'SolidEarth Geotechnics Sdn Bhd supports construction projects through geotechnical investigation, reporting, and foundation advisory.',
        NULL,
        'https://www.solidearth.com.my',
        NULL,
        'Accepts engineering interns'
    ),
    (
        '201801000012',
        'PrimeWorks Project Management Sdn Bhd',
        'Project Management',
        'Project coordination and planning services',
        'PrimeWorks Project Management Sdn Bhd provides project planning, scheduling, monitoring, and coordination services.',
        NULL,
        'https://www.primeworks.com.my',
        NULL,
        'Good opportunity for fresh graduates'
    ),
    (
        '201701000013',
        'Apex Rail Systems Sdn Bhd',
        'Transportation Infrastructure',
        'Railway systems and trackwork services',
        'Apex Rail Systems Sdn Bhd undertakes rail infrastructure works, systems support, and maintenance services.',
        NULL,
        'https://www.apexrail.com.my',
        NULL,
        'Technical roles available'
    ),
    (
        '202101000014',
        'BluePeak BIM Solutions Sdn Bhd',
        'Building Information Modelling',
        'BIM modelling and coordination services',
        'BluePeak BIM Solutions Sdn Bhd supports construction professionals through BIM modelling, clash detection, and coordination.',
        NULL,
        'https://www.bluepeakbim.com.my',
        NULL,
        'Strong fit for IT and construction students'
    ),
    (
        '201901000015',
        'HarborView Construction Sdn Bhd',
        'Construction',
        'Commercial building construction',
        'HarborView Construction Sdn Bhd is a contractor delivering office, retail, and mixed-use commercial projects.',
        NULL,
        'https://www.harborview.com.my',
        NULL,
        'Currently inactive for recruitment'
    ),
    (
        '201601000016',
        'Crestline Facilities Management Sdn Bhd',
        'Facilities Management',
        'Building operation and maintenance',
        'Crestline Facilities Management Sdn Bhd manages building maintenance, asset upkeep, and operational support services.',
        NULL,
        'https://www.crestlinefm.com.my',
        NULL,
        'FM-related vacancies available'
    ),
    (
        '202201000017',
        'Vertex Planning Consult Sdn Bhd',
        'Town Planning',
        'Planning submissions and development advisory',
        'Vertex Planning Consult Sdn Bhd provides development planning consultancy and authority submission services.',
        NULL,
        'https://www.vertexplanning.com.my',
        NULL,
        'Small firm with limited intake'
    ),
    (
        '201401000018',
        'Maju Jaya Material Supply Sdn Bhd',
        'Building Materials',
        'Supply of cement, steel, and finishing materials',
        'Maju Jaya Material Supply Sdn Bhd supplies construction materials to contractors, developers, and project sites.',
        NULL,
        'https://www.majujaya.com.my',
        NULL,
        'May need procurement assistants'
    ),
    (
        '201801000019',
        'Nexus Water Engineering Sdn Bhd',
        'Water Infrastructure',
        'Water treatment and pipeline systems',
        'Nexus Water Engineering Sdn Bhd undertakes water treatment plant, pipeline, and utility infrastructure works.',
        NULL,
        'https://www.nexuswater.com.my',
        NULL,
        'Suspended profile'
    ),
    (
        '202301000020',
        'FutureGrid Energy Solutions Sdn Bhd',
        'Renewable Energy',
        'Solar systems and energy efficiency solutions',
        'FutureGrid Energy Solutions Sdn Bhd provides renewable energy and energy-saving systems for commercial and industrial users.',
        NULL,
        'https://www.futuregrid.com.my',
        NULL,
        'Open to sustainability-related placements'
    );
-- =========================================
-- SAMPLE DATA FOR companybranch
-- =========================================
INSERT INTO companybranch (
        company_id,
        address_line,
        city,
        state,
        postcode,
        country,
        total_no_of_staff,
        vacancy_level,
        status,
        visibility,
        last_visit,
        last_contact,
        is_hq
    )
VALUES (
        1,
        'Level 12, Menara Sentral, Jalan Tun Sambanthan',
        'Kuala Lumpur',
        'Wilayah Persekutuan Kuala Lumpur',
        '50470',
        'Malaysia',
        30,
        'Internship',
        1,
        1,
        '2026-03-20',
        '2026-03-18',
        1
    ),
    (
        1,
        'No. 18, Jalan Teknologi 3/4, Taman Sains Selangor',
        'Petaling Jaya',
        'Selangor',
        '47810',
        'Malaysia',
        15,
        'Entry',
        1,
        1,
        '2026-03-15',
        '2026-03-12',
        0
    ),
    (
        2,
        'No. 25, Jalan SS 2/24, SS 2',
        'Petaling Jaya',
        'Selangor',
        '47300',
        'Malaysia',
        35,
        'Entry',
        1,
        1,
        '2026-03-22',
        '2026-03-19',
        1
    ),
    (
        2,
        'Lot 8, Persiaran Perusahaan, Seksyen 23',
        'Shah Alam',
        'Selangor',
        '40300',
        'Malaysia',
        25,
        'Internship',
        1,
        1,
        '2026-03-16',
        '2026-03-13',
        0
    ),
    (
        3,
        'Suite 9-3, Wisma UOA, Jalan Pinang',
        'Kuala Lumpur',
        'Wilayah Persekutuan Kuala Lumpur',
        '50450',
        'Malaysia',
        18,
        'Internship',
        1,
        1,
        '2026-03-15',
        '2026-03-10',
        1
    ),
    (
        3,
        'No. 11, Jalan Molek 1/10, Taman Molek',
        'Johor Bahru',
        'Johor',
        '81100',
        'Malaysia',
        10,
        'Entry',
        1,
        1,
        '2026-03-12',
        '2026-03-09',
        0
    ),
    (
        4,
        'Menara Metro, Jalan Sultan Ismail',
        'Kuala Lumpur',
        'Wilayah Persekutuan Kuala Lumpur',
        '50250',
        'Malaysia',
        90,
        'Senior',
        1,
        1,
        '2026-03-17',
        '2026-03-14',
        1
    ),
    (
        4,
        'No. 6, Jalan Bestari 5/2, Bandar Bestari',
        'Klang',
        'Selangor',
        '41200',
        'Malaysia',
        50,
        'Entry',
        1,
        1,
        '2026-03-13',
        '2026-03-11',
        0
    ),
    (
        4,
        'No. 88, Jalan Austin Heights 8/3',
        'Johor Bahru',
        'Johor',
        '81100',
        'Malaysia',
        40,
        'Entry',
        1,
        1,
        '2026-03-11',
        '2026-03-10',
        0
    ),
    (
        5,
        'Lot 17, Jalan Industri Utama 2',
        'Seremban',
        'Negeri Sembilan',
        '70400',
        'Malaysia',
        55,
        'Entry',
        1,
        1,
        '2026-03-21',
        '2026-03-16',
        1
    ),
    (
        5,
        'No. 102, Jalan Gopeng',
        'Ipoh',
        'Perak',
        '31350',
        'Malaysia',
        40,
        'Internship',
        1,
        1,
        '2026-03-18',
        '2026-03-15',
        0
    ),
    (
        6,
        'No. 3A, Jalan Kenari 11, Bandar Puchong Jaya',
        'Puchong',
        'Selangor',
        '47170',
        'Malaysia',
        22,
        'Internship',
        1,
        1,
        '2026-03-13',
        '2026-03-11',
        1
    ),
    (
        7,
        'No. 45, Jalan 51A/223',
        'Petaling Jaya',
        'Selangor',
        '46100',
        'Malaysia',
        45,
        'Senior',
        1,
        1,
        '2026-03-24',
        '2026-03-20',
        1
    ),
    (
        7,
        'Ground Floor, Block C, Jalan Dato Keramat',
        'Kuala Lumpur',
        'Wilayah Persekutuan Kuala Lumpur',
        '54000',
        'Malaysia',
        30,
        'Entry',
        1,
        1,
        '2026-03-19',
        '2026-03-16',
        0
    ),
    (
        8,
        'Unit 7-5, Wisma Zelan, Jalan Tasik Permaisuri 2',
        'Cheras',
        'Wilayah Persekutuan Kuala Lumpur',
        '56000',
        'Malaysia',
        20,
        'Entry',
        1,
        1,
        '2026-03-18',
        '2026-03-15',
        1
    ),
    (
        8,
        'No. 29, Jalan Sutera Tanjung 8/4',
        'Skudai',
        'Johor',
        '81300',
        'Malaysia',
        14,
        'Internship',
        1,
        1,
        '2026-03-14',
        '2026-03-12',
        0
    ),
    (
        9,
        'No. 77, Jalan Bukit Gambir',
        'George Town',
        'Pulau Pinang',
        '11700',
        'Malaysia',
        40,
        'Internship',
        0,
        1,
        '2026-03-14',
        '2026-03-12',
        1
    ),
    (
        10,
        'Level 20, Menara Habitat, Jalan Ampang',
        'Kuala Lumpur',
        'Wilayah Persekutuan Kuala Lumpur',
        '50450',
        'Malaysia',
        150,
        'Senior',
        1,
        1,
        '2026-03-19',
        '2026-03-17',
        1
    ),
    (
        10,
        'No. 14, Jalan Bayan Lepas 2',
        'Bayan Lepas',
        'Pulau Pinang',
        '11900',
        'Malaysia',
        90,
        'Entry',
        1,
        1,
        '2026-03-16',
        '2026-03-14',
        0
    ),
    (
        11,
        'No. 12, Jalan Universiti, Seksyen 13',
        'Shah Alam',
        'Selangor',
        '40100',
        'Malaysia',
        18,
        'Internship',
        1,
        1,
        '2026-03-16',
        '2026-03-13',
        1
    ),
    (
        11,
        'Lot 31, Jalan Kuching',
        'Kuching',
        'Sarawak',
        '93100',
        'Malaysia',
        12,
        'Entry',
        1,
        1,
        '2026-03-11',
        '2026-03-09',
        0
    ),
    (
        12,
        'No. 8, Jalan Permas 10/7',
        'Masai',
        'Johor',
        '81750',
        'Malaysia',
        52,
        'Entry',
        1,
        1,
        '2026-03-11',
        '2026-03-09',
        1
    ),
    (
        13,
        'Block B, Technology Park Malaysia, Bukit Jalil',
        'Kuala Lumpur',
        'Wilayah Persekutuan Kuala Lumpur',
        '57000',
        'Malaysia',
        70,
        'Senior',
        1,
        1,
        '2026-03-25',
        '2026-03-21',
        1
    ),
    (
        13,
        'No. 20, Jalan Metro Perdana Barat 1',
        'Kepong',
        'Wilayah Persekutuan Kuala Lumpur',
        '52100',
        'Malaysia',
        50,
        'Entry',
        1,
        1,
        '2026-03-22',
        '2026-03-19',
        0
    ),
    (
        14,
        'No. 55, Jalan Setia Tropika 1/1',
        'Johor Bahru',
        'Johor',
        '81200',
        'Malaysia',
        14,
        'Internship',
        1,
        1,
        '2026-03-10',
        '2026-03-08',
        1
    ),
    (
        14,
        'Level 3, Menara Mutiara, Jalan Raja Chulan',
        'Kuala Lumpur',
        'Wilayah Persekutuan Kuala Lumpur',
        '50200',
        'Malaysia',
        12,
        'Entry',
        1,
        1,
        '2026-03-08',
        '2026-03-07',
        0
    ),
    (
        15,
        'No. 26, Jalan Bukit Minyak 3',
        'Bukit Mertajam',
        'Pulau Pinang',
        '14000',
        'Malaysia',
        88,
        'Entry',
        2,
        1,
        '2026-03-12',
        '2026-03-10',
        1
    ),
    (
        16,
        'No. 91, Jalan Tuanku Abdul Rahman',
        'Kuala Lumpur',
        'Wilayah Persekutuan Kuala Lumpur',
        '50100',
        'Malaysia',
        65,
        'Senior',
        1,
        1,
        '2026-03-23',
        '2026-03-20',
        1
    ),
    (
        16,
        'No. 7, Jalan Diplomatik 2/1, Presint 15',
        'Putrajaya',
        'Wilayah Persekutuan Putrajaya',
        '62050',
        'Malaysia',
        45,
        'Entry',
        1,
        1,
        '2026-03-18',
        '2026-03-16',
        0
    ),
    (
        17,
        'No. 5, Jalan Austin Perdana 2',
        'Johor Bahru',
        'Johor',
        '81100',
        'Malaysia',
        18,
        'Internship',
        1,
        1,
        '2026-03-20',
        '2026-03-17',
        1
    ),
    (
        18,
        'Lot 10, Jalan Perusahaan Sungai Lokan',
        'Butterworth',
        'Pulau Pinang',
        '13400',
        'Malaysia',
        42,
        'Entry',
        1,
        1,
        '2026-03-09',
        '2026-03-07',
        1
    ),
    (
        18,
        'No. 33, Jalan Pending',
        'Kuching',
        'Sarawak',
        '93450',
        'Malaysia',
        25,
        'Internship',
        1,
        1,
        '2026-03-06',
        '2026-03-05',
        0
    ),
    (
        19,
        'No. 60, Jalan Sungai Besi',
        'Kuala Lumpur',
        'Wilayah Persekutuan Kuala Lumpur',
        '57100',
        'Malaysia',
        40,
        'Senior',
        3,
        0,
        '2026-03-26',
        '2026-03-22',
        1
    ),
    (
        19,
        'No. 9, Jalan Lapangan Terbang',
        'Kota Kinabalu',
        'Sabah',
        '88200',
        'Malaysia',
        33,
        'Entry',
        3,
        0,
        '2026-03-21',
        '2026-03-19',
        0
    ),
    (
        20,
        'No. 18, Jalan Solaris 4, Solaris Mont Kiara',
        'Kuala Lumpur',
        'Wilayah Persekutuan Kuala Lumpur',
        '50480',
        'Malaysia',
        20,
        'Internship',
        1,
        1,
        '2026-03-27',
        '2026-03-23',
        1
    ),
    (
        20,
        'No. 21, Jalan Permata 2',
        'Cyberjaya',
        'Selangor',
        '63000',
        'Malaysia',
        15,
        'Entry',
        1,
        1,
        '2026-03-24',
        '2026-03-21',
        0
    );
INSERT INTO studentapplication (
        number_ic,
        studentID,
        studentName,
        gender,
        studentEmail,
        contactDate,
        comName,
        comAddress,
        comSupervisor,
        comSupervisorEmail,
        comSupervisorContact,
        allowance,
        ucSupervisor,
        ucSupervisorEmail,
        ucSupervisorContact,
        applyStatus,
        remark,
        level,
        cohortId,
        programme,
        groupNo,
        CGPA,
        ownTransport,
        tempAddress,
        personalEmail,
        permanentAddress,
        permanentContact,
        healthRemark,
        programmingKnowledge,
        databaseKnowledge,
        networkingKnowledge,
        templateVersion,
        formAcceptance,
        formAcknowledgement,
        letterIdentity,
        otherEvidence,
        doVerifier,
        doVerifierEmail,
        isAgreed
    )
VALUES (
        '010101-10-1234',
        'chuakc-wp22',
        'Chua KC',
        'O',
        'chuakc-wp22@student.tarc.edu.my',
        CURDATE(),
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        0.00,
        NULL,
        NULL,
        NULL,
        'pending',
        NULL,
        1,
        1,
        'SE',
        1,
        0.00,
        0,
        NULL,
        'chuakc-wp22@student.tarc.edu.my',
        NULL,
        NULL,
        NULL,
        'Beginner',
        'Beginner',
        'Beginner',
        1,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        NULL,
        0
    );
INSERT INTO sysuser (
        email,
        username,
        password,
        role,
        is_active,
        is_locked
    )
VALUES (
        'chuakc-wp22@student.tarc.edu.my',
        'chuakc-wp22',
        SHA2('1234', 256),
        'student',
        TRUE,
        FALSE
    );


INSERT INTO notification (
        from_user_id,
        to_user_id,
        type,
        title,
        message,
        is_read,
        created_at
    )
VALUES (
        2,
        1,
        'student_submission',
        'Progress Report Submitted',
        'Student A23BE0123 (Nur Aisyah Binti Hassan) has submitted their progress report for Report #1.',
        0,
        '2026-03-01 09:15:00'
    ),
    (
        2,
        1,
        'student_submission',
        'Progress Report Submitted',
        'Student A23BE0456 (Muhammad Izzat Bin Razak) has submitted their progress report for Report #2.',
        1,
        '2026-03-05 14:30:00'
    ),
    (
        1,
        1,
        'system_alert',
        'Internship Application Pending Review',
        'There is 1 pending internship application awaiting your review and approval.',
        0,
        '2026-03-08 10:00:00'
    ),
    (
        1,
        1,
        'company_update',
        'Company Evaluation Completed',
        'Company evaluation for Alpha Build Sdn Bhd by student A23BE0123 has been completed.',
        1,
        '2026-03-12 16:45:00'
    ),
    (
        1,
        1,
        'system_reminder',
        'Report Deadline Approaching',
        'Progress Report #3 deadline is approaching on 2026-04-07. Please remind students to submit on time.',
        0,
        '2026-03-25 08:00:00'
    ),
    (
        1,
        1,
        'document_review',
        'Document Verification Required',
        'Student A23BE0456 has uploaded supporting documents for verification. Please review.',
        0,
        '2026-03-28 11:20:00'
    ),
    (
        1,
        1,
        'assignment_task',
        'New Student Assignment',
        'You have been assigned to supervise 2 new students for the Feb–Jul 2026 cohort.',
        1,
        '2026-02-15 13:00:00'
    ),
    (
        1,
        1,
        'student_concern',
        'Student Issue Report',
        'Student A23BE0123 has reported a concern regarding workplace support. Please address.',
        0,
        '2026-03-20 15:30:00'
    ),
    (
        1,
        1,
        'system_alert',
        'Evaluation Window Now Open',
        'The student evaluation window is now open. Begin assessing student performance.',
        1,
        '2026-03-10 09:00:00'
    ),
    (
        1,
        1,
        'student_submission',
        'Final Report Submitted',
        'Student A23BE0456 has submitted their final internship report.',
        0,
        '2026-06-25 17:45:00'
    );
