INSERT INTO ucsupervisor (
        staffId,
        name,
        email,
        password,
        contact,
        remark,
        isActive,
        isCommittee,
        faculty,
        campus
    )
VALUES (
        'US0001',
        'Dr. Aina Hassan',
        'aina.hassan@tarc.edu.my',
        'hashed_pw_001',
        '0123456701',
        'Senior lecturer',
        1,
        1,
        'Faculty of Computing and Information Technology',
        'Kuala Lumpur Main Campus'
    ),
    (
        'US0002',
        'Ir. Lim Wei Jian',
        'wei.jian@tarc.edu.my',
        'hashed_pw_002',
        '0123456702',
        'Programme coordinator',
        1,
        0,
        'Faculty of Engineering and Technology',
        'Penang Branch Campus'
    ),
    (
        'US0003',
        'Tan Siew Ling',
        'siew.ling@tarc.edu.my',
        'hashed_pw_003',
        '0123456703',
        'Internship supervisor',
        1,
        0,
        'Faculty of Business and Finance',
        'Perak Branch Campus'
    ),
    (
        'US0004',
        'Goh Chun Keat',
        'chun.keat@tarc.edu.my',
        'hashed_pw_004',
        '0123456704',
        'Faculty representative',
        1,
        1,
        'Faculty of Accountancy, Finance and Business',
        'Johor Branch Campus'
    ),
    (
        'US0005',
        'Nurul Syafiqah',
        'nurul.syafiqah@tarc.edu.my',
        'hashed_pw_005',
        '0123456705',
        'Handles student placement',
        1,
        0,
        'Faculty of Social Science and Humanities',
        'Sabah Branch Campus'
    ),
    (
        'US0006',
        'Farah Nadia',
        'farah.nadia@tarc.edu.my',
        'hashed_pw_006',
        '0123456706',
        'Built environment coordinator',
        1,
        1,
        'Faculty of Built Environment',
        'Sarawak Branch Campus'
    ),
    (
        'US0007',
        'Kevin Lee',
        'kevin.lee@tarc.edu.my',
        'hashed_pw_007',
        '0123456707',
        'Academic advisor',
        1,
        0,
        'Faculty of Computing and Information Technology',
        'Kuala Lumpur Main Campus'
    ),
    (
        'US0008',
        'Suresh Kumar',
        'suresh.kumar@tarc.edu.my',
        'hashed_pw_008',
        '0123456708',
        'Engineering internship liaison',
        1,
        0,
        'Faculty of Engineering and Technology',
        'Penang Branch Campus'
    ),
    (
        'US0009',
        'Patricia Wong',
        'patricia.wong@tarc.edu.my',
        'hashed_pw_009',
        '0123456709',
        'Finance department supervisor',
        1,
        0,
        'Faculty of Business and Finance',
        'Perak Branch Campus'
    ),
    (
        'US0010',
        'Melissa Tan',
        'melissa.tan@tarc.edu.my',
        'hashed_pw_010',
        '0123456710',
        'Committee member',
        1,
        1,
        'Faculty of Accountancy, Finance and Business',
        'Johor Branch Campus'
    ),
    (
        'US0011',
        'Jason Teoh',
        'jason.teoh@tarc.edu.my',
        'hashed_pw_011',
        '0123456711',
        'Student mentor',
        1,
        0,
        'Faculty of Social Science and Humanities',
        'Sabah Branch Campus'
    ),
    (
        'US0012',
        'Sharifah Iman',
        'sharifah.iman@tarc.edu.my',
        'hashed_pw_012',
        '0123456712',
        'Site visit coordinator',
        1,
        0,
        'Faculty of Built Environment',
        'Sarawak Branch Campus'
    ),
    (
        'US0013',
        'Chong Kai Wen',
        'kai.wen@tarc.edu.my',
        'hashed_pw_013',
        '0123456713',
        'Module leader',
        1,
        1,
        'Faculty of Computing and Information Technology',
        'Kuala Lumpur Main Campus'
    ),
    (
        'US0014',
        'Nur Aisyah Rahman',
        'aisyah.rahman@tarc.edu.my',
        'hashed_pw_014',
        '0123456714',
        'Final year project supervisor',
        1,
        0,
        'Faculty of Engineering and Technology',
        'Penang Branch Campus'
    ),
    (
        'US0015',
        'Cheah Mei Ling',
        'mei.ling@tarc.edu.my',
        'hashed_pw_015',
        '0123456715',
        'Industrial training coordinator',
        1,
        1,
        'Faculty of Business and Finance',
        'Perak Branch Campus'
    ),
    (
        'US0016',
        'Ravindran Nair',
        'ravindran.nair@tarc.edu.my',
        'hashed_pw_016',
        '0123456716',
        'Accountancy programme staff',
        1,
        0,
        'Faculty of Accountancy, Finance and Business',
        'Johor Branch Campus'
    ),
    (
        'US0017',
        'Loh Pei Shin',
        'pei.shin@tarc.edu.my',
        'hashed_pw_017',
        '0123456717',
        'Research advisor',
        1,
        0,
        'Faculty of Social Science and Humanities',
        'Sabah Branch Campus'
    ),
    (
        'US0018',
        'Ahmad Faizal',
        'ahmad.faizal@tarc.edu.my',
        'hashed_pw_018',
        '0123456718',
        'Practical training supervisor',
        1,
        1,
        'Faculty of Built Environment',
        'Sarawak Branch Campus'
    ),
    (
        'US0019',
        'Teh Jia Hui',
        'jia.hui@tarc.edu.my',
        'hashed_pw_019',
        '0123456719',
        'Lab coordinator',
        1,
        0,
        'Faculty of Computing and Information Technology',
        'Kuala Lumpur Main Campus'
    ),
    (
        'US0020',
        'Mohd Hakimi',
        'mohd.hakimi@tarc.edu.my',
        'hashed_pw_020',
        '0123456720',
        'Department committee member',
        1,
        1,
        'Faculty of Engineering and Technology',
        'Penang Branch Campus'
    );